TreinaWeb.TesteASPNETMVC/TreinaWeb.TesteASPNETMVC.Web/Models/Pessoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TreinaWeb.TesteASPNETMVC.Web.Models
{
    public class Pessoa
    {
        [Required(ErrorMessage = "O nome é obrigatório")]
        [DisplayName("Nome:")]
        [MaxLength(50, ErrorMessage ="O nome deve ter no maximo 50 caracteres.")]
        [MinLength(5, ErrorMessage ="O nome deve ter no minimo 5 caracteres.")]
        public string Nome { get; set; }

        [DisplayName("Idade:")]
        [Required(ErrorMessage = "O endereço da pessoa é obrigatório")]
        public int Idade { get; set; }

        [DisplayName("Endereço:")]
        [MaxLength(100, ErrorMessage = "O endereço deve ter no máximo 100 caracteres")]
        public string Endereco { get; set; }

        [Required(ErrorMessage = "O e-mail da pessoa é obrigatório")]
        [DisplayName("E-mail:")]
        [MaxLength(80, ErrorMessage = "O e-mail deve ter no máximo 20 caracteres")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }


        public bool Ativo { get; set; }


    }
}

TreinaWeb.TesteASPNETMVC/TreinaWeb.TesteASPNETMVC.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TreinaWeb.TesteASPNETMVC.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TreinaWeb.TesteASPNETMVC/TreinaWeb.TesteASPNETMVC.Web/Controllers/TesteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TreinaWeb.TesteASPNETMVC.Web.Models;

namespace TreinaWeb.TesteASPNETMVC.Web.Controllers
{
    public class TesteController : Controller
    {
        // GET: Teste
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Exclude = "Ativo")]Pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                pessoa.Ativo = true;
                return View("Saudacao", pessoa);
            }

            else
            {
                return View(pessoa);
            }
        }
    }
}

TreinaWeb.TesteASPNETMVC/TreinaWeb.TesteASPNETMVC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>

TreinaWeb.TesteASPNETMVC/TreinaWeb.TesteASPNETMVC.Web/Views/Teste/Index.cshtml
@model TreinaWeb.TesteASPNETMVC.Web.Models.Pessoa

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<br />
<br />
@using (Html.BeginForm("Index", "Teste", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="row">
        <div class="col-sm-1 col-md-1 col-lg-1">
            @Html.LabelFor(p => p.Nome)
        </div>
        <div class="col-sm-12 col-md-8 col-lg-6">
            @Html.EditorFor(p => p.Nome, new { htmlAttributes = new { id = "txtNome", @class = "form-control" } })
            @Html.ValidationMessageFor(p => p.Nome)
        </div>
    </div>
    <div class="row">
        <div class="col-sm-1 col-md-1 col-lg-1">
            @Html.LabelFor(p => p.Idade)
        </div>
        <div class="col-sm-3 col-md-3 col-lg-3">
            @Html.EditorFor(p => p.Idade, new { htmlAttributes = new { id = "txtIdade", @class = "form-control" } })
            @Html.ValidationMessageFor(p => p.Idade)
        </div>
    </div>
    <div class="row">
        <div class="col-sm-1 col-md-1 col-lg-1">
            @Html.LabelFor(p => p.Endereco)
        </div>
        <div class="col-sm-12 col-md-8 col-lg-6">
            @Html.EditorFor(p => p.Endereco, new { htmlAttributes = new { id = "txtEndereco", @class = "form-control" } })
            @Html.ValidationMessageFor(p => p.Endereco)
        </div>
    </div>
    <div class="row">
        <div class="col-sm-1 col-md-1 col-lg-1">
            @Html.LabelFor(p => p.Email)
        </div>
        <div class="col-sm-12 col-md-8 col-lg-6">
            @Html.EditorFor(p => p.Email, new { htmlAttributes = new { id = "txtEmail", @class = "form-control" } })
            @Html.ValidationMessageFor(p => p.Email)
        </div>
    </div>
    <div class="row">
        <input type="submit" value="Enviar" class="btn btn-primary" />
    </div>
}

TreinaWeb.TesteASPNETMVC/TreinaWeb.TesteASPNETMVC.Web/Views/Teste/Saudacao.cshtml
@model TreinaWeb.TesteASPNETMVC.Web.Models.Pessoa
@{
    ViewBag.Title = "Saudacao";
}

<h2>Saudacao</h2>


<p>Olá sejá bem- vindo @Model.Nome</p>
@Html.LabelFor(p => p.Idade)@Html.EditorFor(p => p.Idade)
@Html.LabelFor(p => p.Endereco)@Html.EditorFor(p => p.Endereco)
@Html.LabelFor(p => p.Email)@Html.EditorFor(p => p.Email)